<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01. Beranda_Ujian01_klik_Lihat</name>
   <tag></tag>
   <elementGuidId>f1b96b96-6225-43fe-914f-7e64afdaaf71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bg-yellow-900.text-white.text-center.p-2.rounded-xl.text-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9396848-eb20-4d74-bff0-0d7ae33c7d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-yellow-900 text-white text-center p-2 rounded-xl text-sm</value>
      <webElementGuid>dfaaf6d8-8f89-4323-8275-b6dd713bf7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btn-lihat-event</value>
      <webElementGuid>97d24486-264e-4ebd-a415-939209084451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat</value>
      <webElementGuid>a35a4bb8-6621-490f-974c-3482898d0031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col relative bg-[#F5FFFE]&quot;]/div[1]/div[@class=&quot;relative&quot;]/div[@class=&quot;mx-auto max-w-4xl mb-20&quot;]/div[@class=&quot;mx-auto p-5&quot;]/div[1]/div[@class=&quot;space-y-8&quot;]/div[@class=&quot;grid md:grid-cols-2 gap-4&quot;]/div[@class=&quot;bg-white border border-gray-200 rounded-lg shadow cursor-pointer&quot;]/div[@class=&quot;p-5&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;bg-yellow-900 text-white text-center p-2 rounded-xl text-sm&quot;]</value>
      <webElementGuid>c4a6c46f-7997-4285-b727-d82b87c0b668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>bf86b0ab-2fbf-4e41-aacc-db0c1be2fa87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Durasi'])[1]/following::div[2]</value>
      <webElementGuid>73b92d8c-fba9-424a-b33e-10384f8d44a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtest'])[2]/preceding::div[3]</value>
      <webElementGuid>709b4ff8-a48e-43c5-a1af-e57d92d6c0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat']/parent::*</value>
      <webElementGuid>da900028-a7d7-4459-a01c-b35e8043edb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>38ea45fe-c587-4280-b660-b00f26f1b926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Lihat' or . = 'Lihat')]</value>
      <webElementGuid>09637a1e-354e-4033-9e07-f9fa78c754e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
